sudo: required
services: 
  - docker
before_install:
  - docker build -t afsan007/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run afsan007/react-test npm test
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t afsan007/multi-client ./client
  - docker build -t afsan007/multi-nginx  ./nginx
  - docker build -t afsan007/multi-server ./server
  - docker build -t afsan007/multi-worker ./worker 
  # login to the docker CLI
  # Take all those images and push them to docker hub
  - docker push afsan007/multi-client
  - docker push afsan007/multi-nginx
  - docker push afsan007/multi-server
  - docker push afsan007/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket-name: elasticbeanstalk-us-west-1-30651184564
#   bucket-path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_SECRET_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
